import TopBar from '@/components/TopBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hydraulics',
  description: 'Generated by Hydralics',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar/>
        {children}
      </body>
    </html>
  )
}
