import TopBar from "@/components/TopBar";
import "./globals.css";
import { Inter } from "next/font/google";
import FooterTop from "@/components/FooterTop";
import Footer from "@/components/Footer";
import { Providers } from "./redux/provider";
import { wrapper } from "./redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hydraulics",
  description: "Generated by Hydralics",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <TopBar />
          {children}
          <FooterTop />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}